/**
* @author -         Renz Melecotones (Accenture)
* @date -           19/04/2016
* @description -    A general constant class for Batch Class
* #############Change Log#############
* Modified by     Version     Change Date
**/
public with sharing class AP35_AppConstantForScheduledClass{
    
    
    /*************************************************************************************** 
    Developer -    Renz Melecotones (Accenture Cloud First)
    Date -         19/04/2016
    Version -      1.0 
    Function -     Constant for AP14_CaseAssignmentRuleBatch
    #############Change Log#############
    Modified by     Version     Change Date
    ****************************************************************************************/
    //Sales Region Group
    public static final String CASE_OWNER_QUEUE = 'Queue';  
    public static final String CASE_STATUS_NEW = 'New';
    public static final String QUEUE_CS_URGENT = 'CS-Urgent';    
}