/*
Name: EnquiryManagerTest.cls
Copyright © 2019  Golfbreaks
======================================================
======================================================
Purpose:
-------

Test suite for Enquiry Manager functions.

Coverage for classes below (target 85%):
EnquiryManager.cls : 0%	

======================================================
======================================================
History
------- 
Ver. Author        Date        Detail
1.0  Mark Cane&    2019-05-05  Initial development.
*/
@isTest(SeeAllData=false)
public with sharing class EnquiryManagerTest {
	/*
    Test cases:
        singleTestCase1 - BusinessLogic. todo.
        ..
        negativeTestCase1 - BusinessLogic. todo.
        ..
        bulkTestCase1 - BusinessLogic. todo.
	*/
	
    @testSetup static void setup(){}
    
    /* **/
    static testMethod void singleTestCase1() {
        // Test case 1 : BusinessLogic. todo.

		Test.startTest();
	    
		Test.stopTest();
  	}
    /* */      
}