/*
Name: TestCodeException.cls
Copyright © 2019  Golfbreaks
======================================================
======================================================
Purpose: To facilitate the throwing of custom runtime exceptions
to increase code coverage and validate exception handling in Test Code
-------

======================================================
======================================================
History
------- 
Ver. Author        Date        Detail
1.0  J Radcliffe   2019-07-01  Initial development.
*/
public with sharing class TestCodeException extends Exception {
 
}